### ISSUE TITLE
layout issue, panel shifts to left when when clicked on next image button in COMPUTING panel in FEATURE EXTRACTION PANEL

### ISSUE THREAD

**Issue by getsanjeev** [sumit3203/ACTIVESEGMENTATION#16]
not a big issue, but may be we want to improve it. clicking on next button leads to sub-panels shift to left, on maximizing and then minimizing again it becomes normal.

![computing_panel](https://user-images.githubusercontent.com/20872683/42734698-1699f4a0-8866-11e8-8431-228fe476d123.PNG)

**Comment by sumit3203** [comment]
fixed
