### ISSUE TITLE
Clicking on the 'open project' button does nothing.

### ISSUE THREAD

**Issue by ashraf-rashid** [sumit3203/ACTIVESEGMENTATION#34]
Clicking on the 'open project' button does nothing excepting print 'Windows 10' in the log. 

I'm working on Windows 10 (64 bit) OS. Here's what I did after which I got the bug:

1. Click on 'Create New Project'
2. Give the project name, description as per your need.
3. Select project type - Segmentation
4. While selecting the training image, select an item of the wrong format. For example, I selected a '.jpg' image.
5. Click on finish.
6. Then, click on open project and choose any '.json' file from a previously created project.
7. Click on open. (In my case, nothing happens. It's just 'Windows 10' that gets printed in the log.

This bug only goes away when a new project is created successfully (with all the fields being correctly given) or after restarting ImageJ.

**Comment by dprodanov** [comment]
solved
