### ISSUE TITLE
Some buttons do not work in the feature extraction window

### ISSUE THREAD

**Issue by ashraf-rashid** [sumit3203/ACTIVESEGMENTATION#35]
1. Nothing happens on clicking the 'save' and 'download' buttons in the 'feature extraction' window. Also, there are no outputs in the logs after clicking the buttons. 

2. Sometimes, on clicking the 'compute' button, nothing happens. Sometimes it works fine and prints outputs in the log. 

3. When there is no output on clicking the 'compute' button, none of the windows opened by ImageJ closes on clicking the close button.

**Comment by sumit3203** [comment]
fixed
