### ISSUE TITLE
Creation of many new windows

### ISSUE THREAD

**Issue by ashraf-rashid** [sumit3203/ACTIVESEGMENTATION#39]
An array of new windows get created when I perform the following steps:

1. Click on filter
2. Click on compute
3. Click on close before the 'compute' operation is completed.

The issue can be seen in the screenshot attached.
![Bug on clicking close after clicking compute filter](https://user-images.githubusercontent.com/48878855/55231684-68737c80-5249-11e9-97e7-abf2392cba59.png)

**Comment by ashraf-rashid** [comment]
![Bug on clicking close after clicking compute filter_1](https://user-images.githubusercontent.com/48878855/55231792-b25c6280-5249-11e9-9779-34cf063b6d38.png)

**Comment by sumit3203** [comment]
fixed
