### ISSUE TITLE
Unable to know whether a new classifier has been selected 

### ISSUE THREAD

**Issue by ashraf-rashid** [sumit3203/ACTIVESEGMENTATION#40]
Unable to verify whether a new classifier has been selected or used, as no messages are displayed 
on the GUI after selecting a new classifier. 

Also, clicking on 'save' after selecting a new classifier doesn't work. The values resort back to the
default values after the window is opened after closing.

**Comment by sumit3203** [comment]
Fixed by adding new weka jar.
