### ISSUE TITLE
Save Class - Filters Visualization

### ISSUE THREAD

**Issue by KrUciFieR-Jr** [sumit3203/ACTIVESEGMENTATION#46]
In the Filters Visualization Tab,

Save Class doesn't open any of additional tabs to save the class information.

![saved class](https://user-images.githubusercontent.com/21988185/55684621-c3eceb00-596a-11e9-82a1-38b7d2e678e6.png)

**Comment by sumit3203** [comment]
Add class should not be in Filter visualization. It was wrong functionality and fixed
