### ISSUE TITLE
The visualization of segmentation does not appear after the training?

### ISSUE THREAD

**Issue by piyumalanthony** [sumit3203/ACTIVESEGMENTATION#59]
I tried to recreate an active segmentation based on the provided examples in GitHub https://github.com/dprodanov/indepth_demo using the codebase and the current version seems to be not working training and as a major issue, the process does not output the internal working except the log. In the latest release, the model training procedure doesn't seem to be working well and GUI does not output the segmentation after training.

**Comment by dprodanov** [comment]
Solved.

**Comment by dprodanov** [comment]
Solved in the new release.
